from termcolor import colored, cprint
import time
A=0
B=0
C=0
print("~~~Выбери валюту которую ты хочешь кончентировать!~~~")
print("                     Доллар")
print("ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ    Рубль")
print("                     Теньге")
print("                      Юань")
print("                      Евро")
A=input("Введите валюту которую хотите конвентировать: ")
if A=="Доллар":
    B=float(input("Введите число: "))
    print("В долларах это: ",B*1)
    print("В рублях это: ",B*76.20)
    print("В тенге это: ",B*449.89)
    print("В юанях это: ",B*696.735)
    print("В евро это: ",B*0.9404)
elif A=="Рубль":
    B=float(input("Введите число: "))
    print("В долларах это: ",B*0.0131)
    print("В рублях это: ",B*1)
    print("В тенге это: ",B*6.0852)
    print("В юанях это: ",B*0.0899)
    print("В евро это: ",B*0.0123)
elif A=="Тенге":
    B=float(input("Введите число: "))
    print("В долларах это: ",B*0.0021)
    print("В рублях это: ",B*0.1643)
    print("В тенге это: ",B*1)
    print("В юанях это: ",B*0.0148)
    print("В евро это: ",B*0.002)
elif A=="Юань":
    B=float(input("Введите число: "))
    print("В долларах это: ",B*0.1452)
    print("В рублях это: ",B*11.1226)
    print("В тенге это: ",B*67.6829)
    print("В юанях это: ",B*1)
    print("В евро это: ",B*0.1365)
elif A=="Евро":
    B=float(input("Введите число: "))
    print("В долларах это: ",B*1.0634)
    print("В рублях это: ",B*81.4635)
    print("В тенге это: ",B*495.7195)
    print("В юанях это: ",B*7.3241)
    print("В евро это: ",B*1)
elif A=="HackConsole":
    time.sleep(1.3)
    for step in range(100):
        print(colored("                                                          ", 'green', 'on_black'))
    print(colored("Проверка файлов.                                          ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка файлов..                                         ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка файлов...                                        ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка файлов.                                          ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка файлов..                                         ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка файлов...                                        ", 'green', 'on_black'))
    time.sleep(0.7)
    for step in range(3):
        print(colored("                                                          ", 'green', 'on_black'))
    print(colored("Проверка лицензии.                                        ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка лицензии..                                       ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка лицензии...                                      ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка лицензии.                                        ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка лицензии..                                       ", 'green', 'on_black'))
    time.sleep(0.3)
    print(colored("Проверка лицензии...                                      ", 'green', 'on_black'))
    time.sleep(1.3)
    print(colored("Введите ключ активации консоли!:                          ", 'green', 'on_black'))
    A=input(" ")
    if A== "M&*@RK":
        for step in range(100):
            print(colored("Is the license real?...                                   ", 'green', 'on_black'))
        time.sleep(2.0)
        for step in range(100):
            print(colored("True                                                      ", 'green', 'on_black'))
        time.sleep(1.3)
        for step in range(100):
            print(colored("                                                          ", 'green', 'on_black'))
        print(colored("Проверка пароля.                                          ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Проверка пароля..                                         ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Проверка пароля...                                        ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Проверка пароля.                                          ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Проверка пароля..                                         ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Проверка пароля...                                        ", 'green', 'on_black'))
        time.sleep(1.3)
        for step in range(100):
            print(colored("                                                          ", 'green', 'on_black'))
        print(colored("Авторизация.                                              ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Авторизация..                                             ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Авторизация...                                            ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Авторизация.                                              ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Авторизация..                                             ", 'green', 'on_black'))
        time.sleep(0.3)
        print(colored("Авторизация...                                            ", 'green', 'on_black'))
        time.sleep(1.3)
else:
    print("В списке нет такой валюты! ")
